[package]
name = "day-16"
version = "0.1.0"
edition = "2021"

[dependencies]
glam.workspace = true
itertools.workspace = true
nom.workspace = true
nom_locate.workspace = true
pathfinding = "4"
shared.workspace = true
