[workspace]
members = ["day-*"]
default-members = ["day-*"]
resolver = "2"

[workspace.dependencies]
anyhow = "1"
itertools = "0.14"
nom = "8"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["fmt", "env-filter"] }
