[workspace]
members = ["day-*"]
default-members = ["day-*"]
resolver = "2"

[workspace.dependencies]
itertools = "0.14"
ndarray = "0.16"
nom = "8"
openblas-src = "0.10"

[workspace.dependencies.ndarray-linalg]
version = "0.17"
features = ["openblas"]
