set dotenv-load

dev day part:
  cargo watch -c -w {{day}} -x "t --bin {{part}} -p {{day}}"

run day part:
  cargo run -p {{day}} --bin {{part}}

create day:
  cargo generate --path ./template --name {{day}}
  just get-input {{day}}

get-input day:
  cargo +nightly -Z script get-input.rs --day {{day}} --current-working-directory {{justfile_directory()}}

