[package]
name = "day-06"
version = "0.1.0"
edition = "2021"

[dependencies]
glam.workspace = true
itertools.workspace = true
nom.workspace = true
nom_locate.workspace = true
shared.workspace = true

[dev-dependencies]
rstest.workspace = true
