[package]
name = "day-13"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools.workspace = true
ndarray = "0.16"
ndarray-linalg = { version = "0.17", features = ["openblas"] }
nom.workspace = true
openblas-src = "0.10"
